<?php

/* main.js */
class __TwigTemplate_5477f39b44bbb06372605090b6457dad1cdb55cb41a553d3f0254648570a2cbc extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->parent = false;

        $this->blocks = array(
        );
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        // line 112
        echo "

/* gettext-compatible _ function, example of usage:
 *
 * > // Loading pl_PL.json here (containing polish translation strings generated by tools/i18n_compile.php)
 * > alert(_(\"Hello!\"));
 * Witaj!
 */
function _(s) {
\treturn (typeof l10n != 'undefined' && typeof l10n[s] != 'undefined') ? l10n[s] : s;
}

/* printf-like formatting function, example of usage:
 *
 * > alert(fmt(\"There are {0} birds on {1} trees\", [3,4]));
 * There are 3 birds on 4 trees
 * > // Loading pl_PL.json here (containing polish translation strings generated by tools/locale_compile.php)
 * > alert(fmt(_(\"{0} users\"), [3]));
 * 3 uzytkownikow
 */
function fmt(s,a) {
\treturn s.replace(/\\{([0-9]+)\\}/g, function(x) { return a[x[1]]; });
}

function until(\$timestamp) {
        var \$difference = \$timestamp - Date.now()/1000|0, \$num;
        switch(true){
        case (\$difference < 60):
                return \"\" + \$difference + ' ' + _('second(s)');
        case (\$difference < 3600): //60*60 = 3600
                return \"\" + (\$num = Math.round(\$difference/(60))) + ' ' + _('minute(s)');
        case (\$difference < 86400): //60*60*24 = 86400
                return \"\" + (\$num = Math.round(\$difference/(3600))) + ' ' + _('hour(s)');
        case (\$difference < 604800): //60*60*24*7 = 604800
                return \"\" + (\$num = Math.round(\$difference/(86400))) + ' ' + _('day(s)');
        case (\$difference < 31536000): //60*60*24*365 = 31536000
                return \"\" + (\$num = Math.round(\$difference/(604800))) + ' ' + _('week(s)');
        default:
                return \"\" + (\$num = Math.round(\$difference/(31536000))) + ' ' + _('year(s)');
        }
}

function ago(\$timestamp) {
        var \$difference = (Date.now()/1000|0) - \$timestamp, \$num;
        switch(true){
        case (\$difference < 60) :
                return \"\" + \$difference + ' ' + _('second(s)');
        case (\$difference < 3600): //60*60 = 3600 
                return \"\" + (\$num = Math.round(\$difference/(60))) + ' ' + _('minute(s)');
        case (\$difference <  86400): //60*60*24 = 86400
                return \"\" + (\$num = Math.round(\$difference/(3600))) + ' ' + _('hour(s)');
        case (\$difference < 604800): //60*60*24*7 = 604800
                return \"\" + (\$num = Math.round(\$difference/(86400))) + ' ' + _('day(s)');
        case (\$difference < 31536000): //60*60*24*365 = 31536000
                return \"\" + (\$num = Math.round(\$difference/(604800))) + ' ' + _('week(s)');
        default:
                return \"\" + (\$num = Math.round(\$difference/(31536000))) + ' ' + _('year(s)');
        }
}

var datelocale =
        { days: [_('Sunday'), _('Monday'), _('Tuesday'), _('Wednesday'), _('Thursday'), _('Friday'), _('Saturday')]
        , shortDays: [_(\"Sun\"), _(\"Mon\"), _(\"Tue\"), _(\"Wed\"), _(\"Thu\"), _(\"Fri\"), _(\"Sat\")]
        , months: [_('January'), _('February'), _('March'), _('April'), _('May'), _('June'), _('July'), _('August'), _('September'), _('October'), _('November'), _('December')]
        , shortMonths: [_('Jan'), _('Feb'), _('Mar'), _('Apr'), _('May'), _('Jun'), _('Jul'), _('Aug'), _('Sep'), _('Oct'), _('Nov'), _('Dec')]
        , AM: _('AM')
        , PM: _('PM')
        , am: _('am')
        , pm: _('pm')
        };


function alert(a, do_confirm, confirm_ok_action, confirm_cancel_action) {
      var handler, div, bg, closebtn, okbtn;
      var close = function() {
              handler.fadeOut(400, function() { handler.remove(); });
              return false;
      };

      handler = \$(\"<div id='alert_handler'></div>\").hide().appendTo('body');

      bg = \$(\"<div id='alert_background'></div>\").appendTo(handler);

      div = \$(\"<div id='alert_div'></div>\").appendTo(handler);
      closebtn = \$(\"<a id='alert_close' href='javascript:void(0)'><i class='fa fa-times'></i></div>\")
              .appendTo(div);

      \$(\"<div id='alert_message'></div>\").html(a).appendTo(div);

      okbtn = \$(\"<button class='button alert_button'>\"+_(\"OK\")+\"</button>\").appendTo(div);

      if (do_confirm) {
              confirm_ok_action = (typeof confirm_ok_action !== \"function\") ? function(){} : confirm_ok_action;
              confirm_cancel_action = (typeof confirm_cancel_action !== \"function\") ? function(){} : confirm_cancel_action;
              okbtn.click(confirm_ok_action);
              \$(\"<button class='button alert_button'>\"+_(\"Cancel\")+\"</button>\").click(confirm_cancel_action).click(close).appendTo(div);
              bg.click(confirm_cancel_action);
              okbtn.click(confirm_cancel_action);
              closebtn.click(confirm_cancel_action);
      }

      bg.click(close);
      okbtn.click(close);
      closebtn.click(close);

      handler.fadeIn(400);
}

var saved = {};


var selectedstyle = '";
        echo addslashes($this->getAttribute($this->getAttribute(($context["config"] ?? null), "default_stylesheet", array()), 0, array()));
        // line 114
        echo "';
var styles = {
\t";
        echo "
\t";
        // line 115
        $context['_parent'] = $context;
        $context['_seq'] = twig_ensure_traversable(($context["stylesheets"] ?? null));
        foreach ($context['_seq'] as $context["_key"] => $context["stylesheet"]) {
            echo "'";
            echo addslashes($this->getAttribute($context["stylesheet"], "name", array()));
            echo "' : '";
            echo addslashes($this->getAttribute($context["stylesheet"], "uri", array()));
            // line 116
            echo "',
\t";
        }
        $_parent = $context['_parent'];
        unset($context['_seq'], $context['_iterated'], $context['_key'], $context['stylesheet'], $context['_parent'], $context['loop']);
        $context = array_intersect_key($context, $_parent) + $_parent;
        // line 124
        echo "
};

if (typeof board_name === 'undefined') {
\tvar board_name = false;
}

function changeStyle(styleName, link) {
\t";
        echo "
\t";
        // line 125
        if ($this->getAttribute(($context["config"] ?? null), "stylesheets_board", array())) {
            // line 130
            echo "
\t\tif (board_name) {
\t\t\tstylesheet_choices[board_name] = styleName;
\t\t\tlocalStorage.board_stylesheets = JSON.stringify(stylesheet_choices);
\t\t}
\t";
        } else {
            // line 131
            echo "\t\tlocalStorage.stylesheet = styleName;
\t";
        }
        // line 133
        echo "\t";
        // line 163
        echo "
\t
\tif (!document.getElementById('stylesheet')) {
\t\tvar s = document.createElement('link');
\t\ts.rel = 'stylesheet';
\t\ts.type = 'text/css';
\t\ts.id = 'stylesheet';
\t\tvar x = document.getElementsByTagName('head')[0];
\t\tx.appendChild(s);
\t}
\t
\tdocument.getElementById('stylesheet').href = styles[styleName];
\tselectedstyle = styleName;
\t
\tif (document.getElementsByClassName('styles').length != 0) {
\t\tvar styleLinks = document.getElementsByClassName('styles')[0].childNodes;
\t\tfor (var i = 0; i < styleLinks.length; i++) {
\t\t\tstyleLinks[i].className = '';
\t\t}
\t}
\t
\tif (link) {
\t\tlink.className = 'selected';
\t}
\t
\tif (typeof \$ != 'undefined')
\t\t\$(window).trigger('stylesheet', styleName);
}


";
        echo "
";
        // line 164
        if ($this->getAttribute(($context["config"] ?? null), "stylesheets_board", array())) {
            // line 165
            echo "\t";
            // line 180
            echo "
\t
\tif (!localStorage.board_stylesheets) {
\t\tlocalStorage.board_stylesheets = '{}';
\t}
\t
\tvar stylesheet_choices = JSON.parse(localStorage.board_stylesheets);
\tif (board_name && stylesheet_choices[board_name]) {
\t\tfor (var styleName in styles) {
\t\t\tif (styleName == stylesheet_choices[board_name]) {
\t\t\t\tchangeStyle(styleName);
\t\t\t\tbreak;
\t\t\t}
\t\t}
\t}
\t";
            echo "
";
        } else {
            // line 182
            echo "\t";
            // line 191
            echo "
\tif (localStorage.stylesheet) {
\t\tfor (var styleName in styles) {
\t\t\tif (styleName == localStorage.stylesheet) {
\t\t\t\tchangeStyle(styleName);
\t\t\t\tbreak;
\t\t\t}
\t\t}
\t}
\t";
            echo "
";
        }
        // line 246
        echo "

function init_stylechooser() {
\tvar newElement = document.createElement('div');
\tnewElement.className = 'styles';
\t
\tfor (styleName in styles) {
\t\tvar style = document.createElement('a');
\t\tstyle.innerHTML = '[' + styleName + ']';
\t\tstyle.onclick = function() {
\t\t\tchangeStyle(this.innerHTML.substring(1, this.innerHTML.length - 1), this);
\t\t};
\t\tif (styleName == selectedstyle) {
\t\t\tstyle.className = 'selected';
\t\t}
\t\tstyle.href = 'javascript:void(0);';
\t\tnewElement.appendChild(style);
\t}\t
\t
\tdocument.getElementsByTagName('body')[0].insertBefore(newElement, document.getElementsByTagName('body')[0].lastChild.nextSibling);
}

function get_cookie(cookie_name) {
\tvar results = document.cookie.match ( '(^|;) ?' + cookie_name + '=([^;]*)(;|\$)');
\tif (results)
\t\treturn (unescape(results[2]));
\telse
\t\treturn null;
}

function highlightReply(id) {
\tif (typeof window.event != \"undefined\" && event.which == 2) {
\t\t// don't highlight on middle click
\t\treturn true;
\t}
\t
\tvar divs = document.getElementsByTagName('div');
\tfor (var i = 0; i < divs.length; i++)
\t{
\t\tif (divs[i].className.indexOf('post') != -1)
\t\t\tdivs[i].className = divs[i].className.replace(/highlighted/, '');
\t}
\tif (id) {
\t\tvar post = document.getElementById('reply_'+id);
\t\tif (post)
\t\t\tpost.className += ' highlighted';
\t\t\twindow.location.hash = id;
\t}
\treturn true;
}

function generatePassword() {
\tvar pass = '';
\tvar chars = '";
        echo $this->getAttribute(($context["config"] ?? null), "genpassword_chars", array());
        // line 326
        echo "';
\tfor (var i = 0; i < 8; i++) {
\t\tvar rnd = Math.floor(Math.random() * chars.length);
\t\tpass += chars.substring(rnd, rnd + 1);
\t}
\treturn pass;
}

function dopost(form) {
\tif (form.elements['name']) {
\t\tlocalStorage.name = form.elements['name'].value.replace(/( |^)## .+\$/, '');
\t}
\tif (form.elements['password']) {
\t\tlocalStorage.password = form.elements['password'].value;
\t}
\tif (form.elements['email'] && form.elements['email'].value != 'sage') {
\t\tlocalStorage.email = form.elements['email'].value;
\t}
\t
\tsaved[document.location] = form.elements['body'].value;
\tsessionStorage.body = JSON.stringify(saved);
\t
\treturn form.elements['body'].value != \"\" || (form.elements['file'] && form.elements['file'].value != \"\") || (form.elements.file_url && form.elements['file_url'].value != \"\");
}

function citeReply(id, with_link) {
\tvar textarea = document.getElementById('body');

\tif (!textarea) return false;
\t
\tif (document.selection) {
\t\t// IE
\t\ttextarea.focus();
\t\tvar sel = document.selection.createRange();
\t\tsel.text = '>>' + id + '\\n';
\t} else if (textarea.selectionStart || textarea.selectionStart == '0') {
\t\tvar start = textarea.selectionStart;
\t\tvar end = textarea.selectionEnd;
\t\ttextarea.value = textarea.value.substring(0, start) + '>>' + id + '\\n' + textarea.value.substring(end, textarea.value.length);
\t\t
\t\ttextarea.selectionStart += ('>>' + id).length + 1;
\t\ttextarea.selectionEnd = textarea.selectionStart;
\t} else {
\t\t// ???
\t\ttextarea.value += '>>' + id + '\\n';
\t}
\tif (typeof \$ != 'undefined') {
\t\tvar select = document.getSelection().toString();
\t\tif (select) {
\t\t\tvar body = \$('#reply_' + id + ', #op_' + id).find('div.body');  // TODO: support for OPs
\t\t\tvar index = body.text().indexOf(select.replace('\\n', ''));  // for some reason this only works like this
\t\t\tif (index > -1) {
\t\t\t\ttextarea.value += '>' + select + '\\n';
\t\t\t}
\t\t}

\t\t\$(window).trigger('cite', [id, with_link]);
\t\t\$(textarea).change();
\t}
\treturn false;
}

function rememberStuff() {
\tif (document.forms.post) {
\t\tif (document.forms.post.password) {
\t\t\tif (!localStorage.password)
\t\t\t\tlocalStorage.password = generatePassword();
\t\t\tdocument.forms.post.password.value = localStorage.password;
\t\t}
\t\t
\t\tif (localStorage.name && document.forms.post.elements['name'])
\t\t\tdocument.forms.post.elements['name'].value = localStorage.name;
\t\tif (localStorage.email && document.forms.post.elements['email'])
\t\t\tdocument.forms.post.elements['email'].value = localStorage.email;
\t\t
\t\tif (window.location.hash.indexOf('q') == 1)
\t\t\tciteReply(window.location.hash.substring(2), true);
\t\t
\t\tif (sessionStorage.body) {
\t\t\tvar saved = JSON.parse(sessionStorage.body);
\t\t\tif (get_cookie('";
        echo $this->getAttribute($this->getAttribute(($context["config"] ?? null), "cookies", array()), "js", array());
        // line 328
        echo "')) {
\t\t\t\t// Remove successful posts
\t\t\t\tvar successful = JSON.parse(get_cookie('";
        echo $this->getAttribute($this->getAttribute(($context["config"] ?? null), "cookies", array()), "js", array());
        // line 334
        echo "'));
\t\t\t\tfor (var url in successful) {
\t\t\t\t\tsaved[url] = null;
\t\t\t\t}
\t\t\t\tsessionStorage.body = JSON.stringify(saved);
\t\t\t\t
\t\t\t\tdocument.cookie = '";
        echo $this->getAttribute($this->getAttribute(($context["config"] ?? null), "cookies", array()), "js", array());
        // line 362
        echo "={};expires=0;path=/;';
\t\t\t}
\t\t\tif (saved[document.location]) {
\t\t\t\tdocument.forms.post.body.value = saved[document.location];
\t\t\t}
\t\t}
\t\t
\t\tif (localStorage.body) {
\t\t\tdocument.forms.post.body.value = localStorage.body;
\t\t\tlocalStorage.body = '';
\t\t}
\t}
}

var script_settings = function(script_name) {
\tthis.script_name = script_name;
\tthis.get = function(var_name, default_val) {
\t\tif (typeof tb_settings == 'undefined' ||
\t\t\ttypeof tb_settings[this.script_name] == 'undefined' ||
\t\t\ttypeof tb_settings[this.script_name][var_name] == 'undefined')
\t\t\treturn default_val;
\t\treturn tb_settings[this.script_name][var_name];
\t}
};

function init() {
\tinit_stylechooser();

\t";
        echo "\t
\t";
        // line 363
        if ($this->getAttribute(($context["config"] ?? null), "allow_delete", array())) {
            // line 364
            echo "\tif (document.forms.postcontrols) {
\t\tdocument.forms.postcontrols.password.value = localStorage.password;
\t}
\t";
        }
        // line 368
        echo "\t";
        // line 389
        echo "
\t
\tif (window.location.hash.indexOf('q') != 1 && window.location.hash.substring(1))
\t\thighlightReply(window.location.hash.substring(1));
}

var RecaptchaOptions = {
\ttheme : 'clean'
};

onready_callbacks = [];
function onready(fnc) {
\tonready_callbacks.push(fnc);
}

function ready() {
\tfor (var i = 0; i < onready_callbacks.length; i++) {
\t\tonready_callbacks[i]();
\t}
}

";
        echo "

var post_date = \"";
        // line 391
        echo $this->getAttribute(($context["config"] ?? null), "post_date", array());
        echo "\";
var max_images = ";
        // line 392
        echo $this->getAttribute(($context["config"] ?? null), "max_images", array());
        echo ";

onready(init);

";
        // line 396
        if ($this->getAttribute(($context["config"] ?? null), "google_analytics", array())) {
            // line 398
            echo "

var _gaq = _gaq || [];_gaq.push(['_setAccount', '";
            echo $this->getAttribute(($context["config"] ?? null), "google_analytics", array());
            echo "']);";
            if ($this->getAttribute(($context["config"] ?? null), "google_analytics_domain", array())) {
                echo "_gaq.push(['_setDomainName', '";
                echo $this->getAttribute(($context["config"] ?? null), "google_analytics_domain", array());
                echo "'])";
            }
            if ( !$this->getAttribute(($context["config"] ?? null), "google_analytics_domain", array())) {
                echo "_gaq.push(['_setDomainName', 'none'])";
            }
            echo ";_gaq.push(['_trackPageview']);(function() {var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);})();";
        }
        // line 399
        echo "
";
        // line 400
        if (($this->getAttribute(($context["config"] ?? null), "statcounter_project", array()) && $this->getAttribute(($context["config"] ?? null), "statcounter_security", array()))) {
            // line 401
            echo "var sc = document.createElement('script');
sc.type = 'text/javascript';
sc.innerHTML = 'var sc_project=";
            // line 403
            echo $this->getAttribute(($context["config"] ?? null), "statcounter_project", array());
            echo ";var sc_invisible=1;var sc_security=\"";
            echo $this->getAttribute(($context["config"] ?? null), "statcounter_security", array());
            echo "\";var scJsHost=((\"https:\" == document.location.protocol) ? \"https://secure.\" : \"http://www.\");document.write(\"<sc\"+\"ript type=text/javascript src=\"+scJsHost+\"statcounter.com/counter/counter.js></\"+\"script>\");';
var s = document.getElementsByTagName('script')[0];
s.parentNode.insertBefore(sc, s);
";
        }
        // line 407
        echo "
";
    }

    public function getTemplateName()
    {
        return "main.js";
    }

    public function isTraitable()
    {
        return false;
    }

    public function getDebugInfo()
    {
        return array (  524 => 407,  515 => 403,  511 => 401,  509 => 400,  506 => 399,  490 => 398,  488 => 396,  481 => 392,  477 => 391,  451 => 389,  449 => 368,  443 => 364,  441 => 363,  409 => 362,  400 => 334,  395 => 328,  312 => 326,  256 => 246,  242 => 191,  240 => 182,  220 => 180,  218 => 165,  216 => 164,  182 => 163,  180 => 133,  176 => 131,  168 => 130,  166 => 125,  154 => 124,  147 => 116,  139 => 115,  133 => 114,  19 => 112,);
    }

    /** @deprecated since 1.27 (to be removed in 2.0). Use getSourceContext() instead */
    public function getSource()
    {
        @trigger_error('The '.__METHOD__.' method is deprecated since version 1.27 and will be removed in 2.0. Use getSourceContext() instead.', E_USER_DEPRECATED);

        return $this->getSourceContext()->getCode();
    }

    public function getSourceContext()
    {
        return new Twig_Source("", "main.js", "/var/www/html/vichan/templates/main.js");
    }
}
